### ISSUE TITLE
ensureStorageAccount function can't handle RG names containing "-"

### ISSUE THREAD

**Issue by GeorgeApostolMSFT** [msazurestackworkloads/azurestack-gallery#234]
This function will fail if the resource group name will contain "-" .Example --> RG-AKS

Reason the name of a storage account can't contain "-" uppercase letters or other special characters but this is possible when naming a resource group.

Code function failing.
 
ensureStorageAccount()
{
    SA_NAME="${RESOURCE_GROUP}"

    echo "[$(date +%Y%m%d%H%M%S)][INFO] Ensuring storage account: ${SA_NAME}"
    az storage account create --name ${SA_NAME} --resource-group ${SA_RESOURCE_GROUP} --location ${LOCATION} --sku Premium_LRS --https-only true 1> /dev/null
    if [ $? -ne 0 ]; then
        echo "[$(date +%Y%m%d%H%M%S)][ERR] Error ensuring storage account ${SA_NAME}"
        exit 1
    fi
}

**Comment by GeorgeApostolMSFT** [comment]
Source code --> https://github.com/msazurestackworkloads/azurestack-gallery/releases/tag/diagnosis-v0.1.5 
File --> getkuberneteslogs.sh

**Comment by haofan-ms** [comment]
Hi @GeorgeApostolMSFT , I tried to run the command you mentioned in the ensureStorageAccount(), and it's working fine for resource group name and storage account name with "-".

![image](https://user-images.githubusercontent.com/56602314/140565312-b78957a1-c775-4438-8425-f9c18ed709c8.png)

Also in the script, this ensureStorageAccount() function is used when `--upload-logs` flag is set, which will create resource group and storage account with fixed name and upload the collected logs. The "resource group names contains `-` " scenario should not happen unless the script is manually patched.

![image](https://user-images.githubusercontent.com/56602314/140566108-48a65128-cbb1-4480-905f-c586e29e1012.png)

**Comment by GeorgeApostolMSFT** [comment]
![image](https://user-images.githubusercontent.com/93784824/140567475-844d9207-a9cb-4671-9c5b-46e0b8c8a6fe.png)

**Comment by GeorgeApostolMSFT** [comment]
For me is not working to create a storage account as you did  . Are you using Azure stack hub?

**Comment by haofan-ms** [comment]
Please follow the documentation here (https://github.com/msazurestackworkloads/azurestack-gallery/tree/master/diagnosis#examples) to use the latest scripts. We will update the TSG to resolve confusions.

**Comment by GeorgeApostolMSFT** [comment]
Acknowledged .Thank you for clearing up the confusion.
